# Generated by Django 6.0.1 on 2026-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_rename_session_duration_monitoredapp_session_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
